apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-network-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andusystems-dev-0/andusystems-homelab-iac.git
    targetRevision: HEAD
    path: security/networkpolicies
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
