apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.7.2
      helm:
        valueFiles:
          - $values/apps/longhorn/values.yaml
    - repoURL: https://github.com/andusystems-dev-0/andusystems-homelab-iac.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: longhorn-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
