apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-tailscale
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.102.4
      helm:
        valueFiles:
          - $values/apps/tailscale/values.yaml
    - repoURL: https://github.com/andusystems-dev-0/andusystems-homelab-iac.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: tailscale
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
