controller:
  resources:
    requests: { cpu: 250m, memory: 512Mi }
    limits: { memory: 2Gi }
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
persistence:
  storageClass: longhorn
  size: 8Gi
