apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-pihole
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      targetRevision: 2.38.0
      helm:
        valueFiles:
          - $values/apps/pihole/values.yaml
    - repoURL: https://github.com/andusystems-dev-0/andusystems-homelab-iac.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: pihole
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
