#!/usr/bin/env bash
# Restore Pterodactyl from an S3 backup produced by backup-pterodactyl.sh.
#   restore-pterodactyl.sh [latest|<YYYYMMDDTHHMMSSZ>]   (default: latest)
#
# Rebuilds the split topology: PANEL on the panel VM (docker-compose panel+db+cache+caddy)
# and WINGS as the k3s DaemonSet on the wings node. APP_KEY is restored with the panel
# files, so the node's daemon token stays valid — no re-registration.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/ptero-common.sh"

WANT="${1:-latest}"
if [[ "$WANT" == "latest" ]]; then
  TS="$(aws s3 ls "${S3_BASE}/" | grep -oE '[0-9]{8}T[0-9]{6}Z' | sort | tail -1)"
  [[ -n "$TS" ]] || { echo "No backups found under ${S3_BASE}/" >&2; exit 1; }
else
  TS="$WANT"
fi
SRC="${S3_BASE}/${TS}"
aws s3 ls "${SRC}/panel-db.sql.gz" >/dev/null 2>&1 || { echo "Backup ${SRC} incomplete/missing" >&2; exit 1; }
log "restoring from ${SRC}"

# --- panel VM: docker + stop any existing stack -----------------------------
ssh_panel "command -v docker >/dev/null || (curl -fsSL https://get.docker.com | sudo sh)"
ssh_panel "cd /opt/pterodactyl 2>/dev/null && sudo docker compose down 2>/dev/null || true"

# --- 1) panel files (compose+env+APP_KEY, panel storage, caddy certs) --------
log "restoring panel files..."
aws s3 cp "${SRC}/panel-files.tgz" - | ssh_panel "sudo tar xzf - -C /"

# --- 2) DB: bring up mariadb+redis, then load the dump -----------------------
log "starting database + cache..."
ssh_panel "sudo bash -c 'cd /opt/pterodactyl && docker compose up -d database cache'"
ssh_panel "for i in \$(seq 1 40); do [ \"\$(sudo docker inspect ptero_database --format '{{.State.Health.Status}}' 2>/dev/null)\" = healthy ] && break; sleep 3; done"
log "loading panel DB..."
aws s3 cp "${SRC}/panel-db.sql.gz" - | gunzip \
  | ssh_panel "sudo docker exec -i ptero_database sh -c 'exec mariadb -uroot -p\"\$MARIADB_ROOT_PASSWORD\"'"

# --- 3) regenerate panel node-resolution override, then bring up panel + TLS -
log "writing panel node-resolution override + starting panel..."
{
  printf '# generated by restore-pterodactyl.sh — panel reaches each wings node direct on the LAN\n'
  printf 'services:\n  panel:\n    extra_hosts:\n'
  for entry in "${GAME_NODES[@]}"; do IFS=: read -r fqdn ip ds secret <<<"$entry"; printf '      - "%s:%s"\n' "$fqdn" "$ip"; done
} | ssh_panel "sudo tee /opt/pterodactyl/docker-compose.override.yml >/dev/null"
ssh_panel "sudo bash -c 'cd /opt/pterodactyl && docker compose up -d panel && docker compose --profile tls up -d tls'"
ssh_panel "for i in \$(seq 1 40); do [ \"\$(curl -s -o /dev/null -w '%{http_code}' http://localhost/ 2>/dev/null)\" = 200 ] && break; sleep 3; done"

# --- 4) per node: restore volumes + regenerate wings-config from the panel ---
ssh_k3s "$KUBECTL create namespace pterodactyl --dry-run=client -o yaml | $KUBECTL apply -f - >/dev/null"
for entry in "${GAME_NODES[@]}"; do
  IFS=: read -r fqdn ip ds secret <<<"$entry"; key="$(node_key "$fqdn")"
  if aws s3 ls "${SRC}/volumes-${key}.tgz" >/dev/null 2>&1; then
    log "restoring volumes to ${key} (${ip})..."
    ssh_host "$ip" "sudo mkdir -p /var/lib/pterodactyl"
    aws s3 cp "${SRC}/volumes-${key}.tgz" - | ssh_host "$ip" "sudo tar xzf - -C /var/lib"
  fi
  # Regenerate the daemon config from the restored panel so the token always matches
  # the DB (survives any panel-side node edit/token reset). Fall back to the saved secret.
  NID="$(ssh_panel "sudo docker exec ptero_panel php artisan tinker --execute='echo optional(\Pterodactyl\Models\Node::where(\"fqdn\",\"${fqdn}\")->first())->id;'" 2>/dev/null | tr -dc '0-9')"
  if [[ -n "$NID" ]]; then
    log "regenerating ${secret} from panel (node id ${NID})..."
    ssh_panel "sudo docker exec ptero_panel php artisan p:node:configuration ${NID}" 2>/dev/null \
      | python3 "$REPO_ROOT/scripts/lib/wings-config-ssl.py" \
      | ssh_k3s "$KUBECTL create secret generic ${secret} -n pterodactyl --from-file=config.yml=/dev/stdin --dry-run=client -o yaml | $KUBECTL apply -f - >/dev/null"
  elif aws s3 ls "${SRC}/${secret}.yml" >/dev/null 2>&1; then
    log "restoring saved ${secret} (panel lookup failed)..."
    aws s3 cp "${SRC}/${secret}.yml" - \
      | ssh_k3s "$KUBECTL create secret generic ${secret} -n pterodactyl --from-file=config.yml=/dev/stdin --dry-run=client -o yaml | $KUBECTL apply -f - >/dev/null"
  fi
done

# --- 5) inject panel hostAlias into each wings DaemonSet + restart -----------
log "injecting panel hostAlias into wings daemonsets..."
for entry in "${GAME_NODES[@]}"; do
  IFS=: read -r fqdn ip ds secret <<<"$entry"
  ssh_k3s "for i in \$(seq 1 40); do $KUBECTL -n pterodactyl get ds/${ds} >/dev/null 2>&1 && break; sleep 5; done
  $KUBECTL -n pterodactyl patch daemonset ${ds} --type merge -p '{\"spec\":{\"template\":{\"spec\":{\"hostAliases\":[{\"ip\":\"${PANEL_HOST}\",\"hostnames\":[\"pterodactyl.andusystems.com\"]}]}}}}' >/dev/null 2>&1 || true
  $KUBECTL -n pterodactyl rollout restart daemonset/${ds} >/dev/null 2>&1 || true"
done

# --- 6) verify all nodes online ----------------------------------------------
log "verifying nodes online..."
ssh_panel "sudo docker exec ptero_panel php artisan tinker --execute='foreach(\Pterodactyl\Models\Node::all() as \\\$n){ try{ \\\$s=app(\Pterodactyl\Repositories\Wings\DaemonConfigurationRepository::class)->setNode(\\\$n)->getSystemInformation(); echo \\\$n->name.\": ONLINE\n\"; }catch(\Throwable \\\$e){ echo \\\$n->name.\": offline\n\"; } }'" 2>/dev/null | grep -iE 'ONLINE|offline'
log "restore complete from ${TS}."
