apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 91.5.2
      helm:
        valueFiles:
          - $values/apps/prometheus/values.yaml
    - repoURL: https://github.com/andusystems-dev-0/andusystems-homelab-iac.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
