grafana:
  enabled: false
prometheus:
  prometheusSpec:
    retention: 15d
    resources:
      requests: { cpu: 200m, memory: 1Gi }
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
alertmanager:
  alertmanagerSpec:
    resources:
      requests: { cpu: 25m, memory: 64Mi }
